#!/bin/bash
## install essential tools for my development environment
## -----

if [[ "$OSTYPE" != "darwin"* ]]; then
  echo "unsupported os."
  exit
fi

function init() {
  echo "[-] installing xcode command line tools [-]"
  xcode-select --install

  if ! hash brew &> /dev/null; then
    echo "[-] installing homebrew [-]"
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    (echo; echo 'eval "$(/opt/homebrew/bin/brew shellenv)"') >> ~/.zprofile
    eval "$(/opt/homebrew/bin/brew shellenv)"
  fi
}
init

echo "[-] installing some prerequisite packages [-]"
brew update
brew install curl wget git coreutils watch ncdu jq fd

echo "[-] installing source code pro font [-]"
brew install --cask font-jetbrains-mono-nerd-font

function backup() {
  local backup_dir=dotfiles-bak-$(date +%s)

  mkdir ~/$backup_dir
  mv ~/.zshrc ~/$backup_dir/.zshrc
  mv ~/.zshenv ~/$backup_dir/.zshenv
}
echo "[-] backing up dotfiles [-]"
backup

function linking() {
  ln -s $(pwd)/.zshrc ~/.zshrc
  ln -s $(pwd)/.zshenv ~/.zshenv
  ln -s $(pwd)/.gitignore ~/.gitignore
  ln -s $(pwd)/.vimrc ~/.vimrc
  ln -s $(pwd)/.fdignore ~/.fdignore
  ln -s $(pwd)/.ideavimrc ~/.ideavimrc

  mkdir -p ${XDG_CONFIG_HOME:=~/.config}
  ln -s $(pwd)/ghostty $XDG_CONFIG_HOME/ghostty
}
echo "[-] linking dotfiles [-]"
linking

echo "[-] installing extended packages [-]"
brew install zsh-autosuggestions parallel ripgrep fzf
brew install httpie pyenv universal-ctags

echo "[-] downloading git-prompt.sh script [-]"
mkdir -p ~/.zsh/plugins/git/
curl https://raw.githubusercontent.com/git/git/master/contrib/completion/git-prompt.sh -o ~/.zsh/plugins/git/git-prompt.sh

echo "[-] installing ghostty [-]"
brew install ghostty

# echo "[-] change default shell to zsh [-]"
# chsh -s $(which zsh)
echo "[-] Setup done. Run \`source ~/.zshrc\` to refresh shell config [-]"
